### ISSUE TITLE
Stuck in form

### ISSUE THREAD

**Issue by manuxi** [bitExpert/sulu-securitytxt-bundle#256]
Since I was curious how to save the "webspaces" (see https://github.com/sulu/sulu-demo/pull/106#issuecomment-2199758276) I had to make some changes to make this bundle to work - composer & some security constants. But now I'm stuck. Form doesnt save. do:sch:up was done... Latest Sulu 2.6.4 used. 
![image](https://github.com/user-attachments/assets/40a5c40d-a34c-4c08-a29c-40f66478b491)
Please advice.

**Comment by manuxi** [comment]
after adding the contents of securitytxt_admin.yaml to routes_admin. yaml I get it to work.

**Comment by shochdoerfer** [comment]
Not sure if I can follow. Do you want to add a new feature to this bundle? Any help needed?

**Comment by manuxi** [comment]
Thank you for that offer. 
Since I'm working on a project with two webspaces I tried to evaluate how to make webspace specific settings. I wanted to see how you'd solved the problem with the 'missing' webspace in the demo pr. Got your bundle wo work after some tweaks but I'm not sure whether doing the same or using just snippets. Seems confusing to me to see both settings elements in the list within one webspace.
